version: 2
models:
- name: customer_churn_risk_mart
  description: Model for customer_churn_risk_mart in marts schema.
  columns:
  - name: customer_id
    description: Column customer_id with type integer
    data_type: integer
  - name: customer_name
    description: Column customer_name with type character varying
    data_type: character varying(255)
  - name: customer_email
    description: Column customer_email with type character varying
    data_type: character varying(255)
  - name: registration_date
    description: Column registration_date with type date
    data_type: date
  - name: last_order_date
    description: Column last_order_date with type timestamp without time zone
    data_type: timestamp without time zone
  - name: days_since_last_order
    description: Column days_since_last_order with type integer
    data_type: integer
  - name: total_orders
    description: Column total_orders with type bigint
    data_type: bigint
  - name: avg_order_value
    description: Column avg_order_value with type numeric
    data_type: numeric(10,2)
  - name: churn_risk_score
    description: Column churn_risk_score with type numeric
    data_type: numeric(10,2)
  - name: churn_risk_segment
    description: Column churn_risk_segment with type character varying
    data_type: character varying(255)
  - name: analysis_date
    description: Column analysis_date with type date
    data_type: date
- name: orders_customers_mart
  description: Model for orders_customers_mart in marts schema.
  columns:
  - name: order_id
    description: Column order_id with type integer
    data_type: integer
  - name: customer_id
    description: Column customer_id with type integer
    data_type: integer
  - name: customer_name
    description: Column customer_name with type character varying
    data_type: character varying(255)
  - name: customer_email
    description: Column customer_email with type character varying
    data_type: character varying(255)
  - name: order_date
    description: Column order_date with type timestamp without time zone
    data_type: timestamp without time zone
  - name: total_amount
    description: Column total_amount with type numeric
    data_type: numeric(10,2)
  - name: registration_date
    description: Column registration_date with type date
    data_type: date
- name: orders_mart
  description: Model for orders_mart in marts schema.
  columns:
  - name: order_id
    description: Column order_id with type integer
    data_type: integer
  - name: customer_id
    description: Column customer_id with type integer
    data_type: integer
  - name: order_date
    description: Column order_date with type timestamp without time zone
    data_type: timestamp without time zone
  - name: total_amount
    description: Column total_amount with type numeric
    data_type: numeric(10,2)
  - name: product_id
    description: Column product_id with type integer
    data_type: integer
  - name: quantity
    description: Column quantity with type integer
    data_type: integer
  - name: price
    description: Column price with type numeric
    data_type: numeric(10,2)
  - name: item_total
    description: Column item_total with type numeric
    data_type: numeric(10,2)
- name: orders_products_mart
  description: Model for orders_products_mart in marts schema.
  columns:
  - name: order_id
    description: Column order_id with type integer
    data_type: integer
  - name: customer_id
    description: Column customer_id with type integer
    data_type: integer
  - name: order_date
    description: Column order_date with type timestamp without time zone
    data_type: timestamp without time zone
  - name: total_amount
    description: Column total_amount with type numeric
    data_type: numeric(10,2)
  - name: product_id
    description: Column product_id with type integer
    data_type: integer
  - name: product_name
    description: Column product_name with type character varying
    data_type: character varying(255)
  - name: product_category
    description: Column product_category with type character varying
    data_type: character varying(255)
  - name: item_price
    description: Column item_price with type numeric
    data_type: numeric(10,2)
  - name: product_price
    description: Column product_price with type numeric
    data_type: numeric(10,2)
  - name: quantity
    description: Column quantity with type integer
    data_type: integer
  - name: product_created_date
    description: Column product_created_date with type date
    data_type: date
